plugins {
    alias(libs.plugins.buildorbreak.android.application)
    alias(libs.plugins.buildorbreak.android.compose)
    alias(libs.plugins.buildorbreak.android.hilt)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.baselineprofile)
    alias(libs.plugins.roborazzi)
}

android {
    namespace = "com.buildorbreak.app"

    lint {
        // Lint is wrong about this one. It reports mipmap-anydpi-v26 as a
        // redundant qualifier because minSdk is already 26, and merging the
        // folder into mipmap-anydpi as it suggests makes AAPT fail to link the
        // launcher icon at all. The qualifier stays.
        disable += "ObsoleteSdkInt"
    }

    defaultConfig {
        applicationId = "com.buildorbreak.app"
    }

    buildFeatures {
        buildConfig = true
    }

    androidComponents {
        /*
         * Unit tests run on debug only.
         *
         * Compose UI tests need androidx.compose.ui:ui-test-manifest, which
         * supplies the activity they render into and is deliberately a debug
         * only dependency: shipping it in a release would put test scaffolding
         * in the APK. Running the same tests twice against a variant that
         * cannot host them adds no coverage, since unit tests never go through
         * R8 or the release manifest anyway.
         */
        beforeVariants(selector().withBuildType("release")) { variant ->
            variant.enableUnitTest = false
        }
    }
}

dependencies {
    implementation(projects.core.model)
    implementation(projects.core.domain)
    implementation(projects.core.common)
    implementation(projects.core.data)
    implementation(projects.core.designsystem)
    implementation(projects.scheduler)
    implementation(projects.billing)
    implementation(projects.widget)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.splashscreen)
    implementation(libs.androidx.startup)

    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(libs.hilt.navigation.compose)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.collections.immutable)

    // Ships the baseline profile generated by :benchmark. See techspec.md
    // section 9. Without this the profile is generated but never applied.
    implementation(libs.androidx.profileinstaller)
    baselineProfile(projects.benchmark)

    testImplementation(projects.core.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.roborazzi.rule)
    testImplementation(libs.androidx.compose.ui.test.junit4)

    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.espresso.core)
}

// Feature packages live inside this module for now: today, plan, insights,
// settings, onboarding, paywall.
//
// techspec.md section 3 gives the promotion rule: split a package into its own
// :feature module only when it exceeds roughly fifteen files, or when a clean
// build of :app passes forty five seconds. Not before.
